package com.realthon.etf.global.exception;

public enum ClientExceptionCode {

    // 전체
    INTERNAL_SERVER_ERROR,
    ILLEGAL_ARGUMENT,

    // 인증
    LOGIN_ERROR,
    AUTH_SERVER_ERROR,
    AUTH_TOKEN_EMPTY,
    ACCESS_TOKEN_EMPTY,
    REFRESH_TOKEN_EMPTY,
    AUTH_TOKEN_EXPIRED,
    AUTH_TOKEN_INVALID,
    AUTH_TOKEN_MISMATCH,
    FORBIDDEN,

    // 사용자
    USER_NOT_FOUND,
    INVALID_PASSWORD,
    DUPLICATE_LOGIN_ID,
    DUPLICATE_EMAIL,
    DUPLICATE_PHONE_NUMBER,

    // 이력서
    RESUME_FILE_REQUIRED,
    RESUME_SUMMARY_NOT_FOUND,

    // 내 웹 사이트
    TARGET_URL_NOT_FOUND,
    TARGET_URL_DUPLICATED,

    // 알림
    NOTIFICATION_NOT_FOUND,

    // AI
    AI_REQUEST_NOT_FOUND,
    AI_CALLBACK_UNAUTHORIZED,
    AI_ALREADY_COMPLETED,
    AI_CRAWLER_CALL_FAILED

}
