spring:
  application:
    name: etf
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    access-ttl: 900000
    refresh-ttl: 604800000

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    whitelabel:
      enabled: false
