spring:
  application:
    name: etf
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    access-ttl: 900000
    refresh-ttl: 604800000

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
    com.realthon.etf: DEBUG     # 우리 코드 영역 전반
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG      # 실행 SQL
    org.hibernate.orm.jdbc.bind: TRACE  # 바인딩 파라미터(값)까지